### ISSUE TITLE
Problem with caching

### ISSUE THREAD

**Issue by roxik** [spiritix/lada-cache#47] opened 2017-10-01 14:33 UTC
I have a problem. At some point of time the cache of the following request ceases to be updated for the unknown reasons. 

```
$newProducts = $product->catalogItem()
->whereNotNull('available')
->whereNull('preorder')
->orderBy('release_date', 'desc')
->limit($limitProductsOnTabs)
->get();

public function scopeCatalogItem($query)
{
return $query->select('products.id', 'image', 'name', 'rrp', 'wmr', 'activation_id', 'slug', 'has_discount', getNameCurr())->with('activation')->with('genres');
}
```

But the page of product is successfully cached. Why?

**Comment by roxik** [comment] 2017-10-02 09:50
I have noticed that it after a mistake.

[2017-10-02 05:00:06] production.ERROR: ErrorException: Undefined index: aggregate in vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1775
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1775): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/p...', 1775, Array)
#1 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(689): Illuminate\Database\Query\Builder->getCountForPagination()
#2 //app/Http/Controllers/Api/CatalogController.php(130): Illuminate\Database\Eloquent\Builder->paginate(20)

**Comment by spiritix** [comment] 2017-10-03 07:42
Hi, I don't think that this error is related to Lada Cache. Please post the entire stack trace.

**Comment by Swanty** [comment] 2017-10-03 09:03
@spiritix I think it might be related, but not sure if it's a problem with lada cache specifically, just simply related, because I've been having these errors randomly popup for me too.
It's weird, because I can't reproduce it, but it might be something related to perfect timing as in when cache gets invalidated from Redis.
I get these errors every single day at random times, in random models.

Could it be related to issue #46 ?
Because all these aggregate errors are because of trying to get count.

```
Stack trace:
#0 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2061): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/data/www/relea...', 2061, Array)
#1 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1969): Illuminate\Database\Query\Builder->aggregate('count', Array)
#2 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->count()
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('count', Array)
#4 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(344): call_user_func_array(Array, Array)
#5 /data/www/releases/20170929134649/vendor/relay/core/src/NodeTraitShared.php(28): Illuminate\Database\Eloquent\Relations\Relation->__call('count', Array)
#6 /data/www/releases/20170929134649/vendor/relay/core/src/NodeTraitShared.php(125): Relay\Article\Article->getRelationCount('comments')
#7 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(11480): Relay\Article\Article->getCommentsCountAttribute(NULL)
#8 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(11440): Illuminate\Database\Eloquent\Model->mutateAttribute('comments_count', NULL)
#9 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(11429): Illuminate\Database\Eloquent\Model->getAttributeValue('comments_count')
#10 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(11791): Illuminate\Database\Eloquent\Model->getAttribute('comments_count')
#11 /data/www/storage/framework/views/3b696e739acb3330f64950ec77ac78773283b0f3.php(36): Illuminate\Database\Eloquent\Model->__get('comments_count')
#12 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15648): include('/data/www/stora...')
#13 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15685): Illuminate\View\Engines\PhpEngine->evaluatePath('/data/www/stora...', Array)
#14 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15517): Illuminate\View\Engines\CompilerEngine->get('/data/www/relea...', Array)
#15 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15505): Illuminate\View\View->getContents()
#16 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15489): Illuminate\View\View->renderContents()
#17 /data/www/storage/framework/views/3ea2da1d7695aeff40b816a8dcb6b74b11d13adb.php(10): Illuminate\View\View->render()
#18 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15648): include('/data/www/stora...')
#19 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15685): Illuminate\View\Engines\PhpEngine->evaluatePath('/data/www/stora...', Array)
#20 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15517): Illuminate\View\Engines\CompilerEngine->get('/data/www/relea...', Array)
#21 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15505): Illuminate\View\View->getContents()
#22 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15489): Illuminate\View\View->renderContents()
#23 /data/www/storage/framework/views/a41ee264ec46c0fdaf9257809539311398a2293b.php(62): Illuminate\View\View->render()
#24 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15648): include('/data/www/stora...')
#25 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15685): Illuminate\View\Engines\PhpEngine->evaluatePath('/data/www/stora...', Array)
#26 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15517): Illuminate\View\Engines\CompilerEngine->get('/data/www/relea...', Array)
#27 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15505): Illuminate\View\View->getContents()
#28 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15489): Illuminate\View\View->renderContents()
#29 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15524): Illuminate\View\View->render()
#30 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15517): Illuminate\View\View->gatherData()
#31 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15505): Illuminate\View\View->getContents()
#32 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(15489): Illuminate\View\View->renderContents()
#33 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(16762): Illuminate\View\View->render()
#34 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(16249): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#35 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(8509): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#36 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(8355): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#37 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /data/www/releases/20170929134649/app/Http/Middleware/VarnishCache.php(11): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(10069): App\Http\Middleware\VarnishCache->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(8356): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(8347): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#44 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(8338): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 /data/www/releases/20170929134649/vendor/relay/core/src/Http/Middleware/RedirectIndexPhp.php(48): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(10069): Relay\Core\Http\Middleware\RedirectIndexPhp->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /data/www/releases/20170929134649/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /data/www/releases/20170929134649/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /data/www/releases/20170929134649/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}
```

**Comment by roxik** [comment] 2017-10-03 11:23
@spiritix 
`[2017-10-03 06:15:03] production.ERROR: ErrorException: Undefined index: aggregate in /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1775
Stack trace:
#0 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1775): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/p11839...', 1775, Array)
#1 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(689): Illuminate\Database\Query\Builder->getCountForPagination()
#2 /var/www/p118396/data/www/app/Http/Controllers/Api/CatalogController.php(131): Illuminate\Database\Eloquent\Builder->paginate(20)
#3 [internal function]: App\Http\Controllers\Api\CatalogController->index(Object(Illuminate\Http\Request), Object(Illuminate\Database\Eloquent\Builder))
#4 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#5 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#6 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\CatalogController), 'index')
#7 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#8 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#9 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /var/www/p118396/data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /var/www/p118396/data/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}  
`

after a error or not the list of products ceases to be cached

**Comment by spiritix** [comment] 2017-10-03 11:30
What Laravel version are you guys using?

**Comment by roxik** [comment] 2017-10-03 11:32
5.4.

perhaps not because of it, but why after a while ceases to cache the list of products? the page of product well

**Comment by roxik** [comment] 2017-10-03 11:38
Maybe doesn't manage to cache? In day the resource visits 10k users

**Comment by spiritix** [comment] 2017-10-03 11:42
Ok, so I think we need to differentiate between the error message you guys reported and the problem that some queries are not cached resp. not properly invalidated. The error message is definitely not related to Lada Cache, since you can see in the stack trace that Lada Cache doesn't even get called at any time. Regarding the cache problem, I will close this issue in favor to #46, because as @Swanty already mentioned, it seems to be related. Lada Cache currently isn't able to properly handle sub-queries which is definitely an important issue.

**Closed by spiritix** 2017-10-03 11:42 UTC

**Comment by roxik** [comment] 2017-10-03 11:46
This mistake is related with the catalog where there is a pagination, it ceases to be cached too.

But the list of products without pagination and subqueries why ceases to be cached?

**Comment by spiritix** [comment] 2017-10-03 11:52
@roxik Please enable [DebugBar](https://github.com/barryvdh/laravel-debugbar) and check what queries your code generates, which of them get cached when they get invalidated by Lada Cache. I am pretty sure your query for the products list does get cached but somehow invalidated afterward.

**Comment by roxik** [comment] 2017-10-03 12:03
[Hit] select `id`, `image`, `name`, `rrp`, `wmr`, `activation_id`, `slug`, `has_discount`, `wmr` from `products` where `available` is not null and `preorder` is null order by `release_date` desc limit 8 (303μs)

but data have been updated

**Comment by spiritix** [comment] 2017-10-03 12:04
So if I get you right, this query still returns the old data even though another query has updated the data in the meantime? Could you please post the query which updates the data as well?

**Comment by roxik** [comment] 2017-10-03 12:08
I updated data through eloquent in the database, but lada-cache did not update them, only lada-cache:flush helps. But so not always, and begins after a while. With other requests so far everything is OK, only with the list of goods, and all requests with the list of goods.

**Comment by spiritix** [comment] 2017-10-03 12:11
Ok, I understand. Please post the SQL of the query which does the update. You should see it in the DebugBar as well.

**Comment by roxik** [comment] 2017-10-03 12:15
update `products` set `preorder` = '', `rrp` = '1999', `release_date` = '2017-10-10 00:00:00', `updated_at` = '2017-10-03 15:15:02' where `id` = '3443'

**Comment by roxik** [comment] 2017-10-03 12:39
there can be a problem because of the synchronous request by the row?

**Comment by spiritix** [comment] 2017-10-03 12:45
Just tested this using a unit test. The invalidation works fine with your provided example. Therefore the issue must be caused by a query being fired and not handled by Lada Cache. And this is exactly the problem we have at #46, Laravel builds some queries in Eloquent\Builder instead of Query\Builder where Lada Cache is not involved at all. Strange is that you say it only occurs sometimes, are you sure about that?

**Comment by roxik** [comment] 2017-10-03 14:02
Yes, I am sure

**Comment by spiritix** [comment] 2017-10-03 14:16
Ok, then please refer to the conversation in [here](https://github.com/spiritix/lada-cache/issues/46). If it can't be consistently reproduced, there must be a mechanism which deletes keys in Redis from time to time.
